pipeline{
    agent any

    stages{
        stage('init'){
            steps{
                sh 'terraform init -no-color'
            }
        }
        stage('validatet'){
            steps{
                sh 'terraform validate -no-color'
            }
        }
    }
}